apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: gaming-platform
data:
  Jwt__Issuer: "gaming-backend-platform/identity"
  Jwt__Audiences__0: "gbp-player"
  Jwt__Audiences__1: "gbp-admin"
  Jwt__ClockSkewSeconds: "30"
