apiVersion: batch/v1
kind: Job
metadata:
  name: identity-migrator
  namespace: gaming-platform
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: identity-migrator
    spec:
      restartPolicy: OnFailure
      containers:
        - name: identity-migrator
          image: ghcr.io/alex-shepel-oo/identity-migrator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ConnectionStrings__IdentityDb
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: ConnectionStrings__IdentityDb
