<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Quartz" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
  </ItemGroup>

</Project>
