// <auto-generated />
using System;
using EconomyService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EconomyService.Persistence.Migrations
{
    [DbContext(typeof(EconomyDbContext))]
    [Migration("20260719182455_AddProcessedMessages")]
    partial class AddProcessedMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EconomyService.Domain.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_balances");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_balances_currency_id");

                    b.HasIndex("UserId", "CurrencyId")
                        .IsUnique()
                        .HasDatabaseName("ix_balances_user_id_currency_id");

                    b.ToTable("balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_balances_amount_non_negative", "amount >= 0");
                        });
                });

            modelBuilder.Entity("EconomyService.Domain.ConversionRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_currency_id");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate");

                    b.Property<Guid>("ToCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_currency_id");

                    b.HasKey("Id")
                        .HasName("pk_conversion_rates");

                    b.HasIndex("ToCurrencyId")
                        .HasDatabaseName("ix_conversion_rates_to_currency_id");

                    b.HasIndex("FromCurrencyId", "ToCurrencyId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversion_rates_from_currency_id_to_currency_id");

                    b.ToTable("conversion_rates", (string)null);
                });

            modelBuilder.Entity("EconomyService.Domain.ConversionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<decimal>("FromAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("from_amount");

                    b.Property<Guid>("FromCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_currency_id");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<decimal>("RateApplied")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("rate_applied");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("ToAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("to_amount");

                    b.Property<Guid>("ToCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_currency_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_conversion_requests");

                    b.HasIndex("FromCurrencyId")
                        .HasDatabaseName("ix_conversion_requests_from_currency_id");

                    b.HasIndex("ToCurrencyId")
                        .HasDatabaseName("ix_conversion_requests_to_currency_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_conversion_requests_user_id_status");

                    b.ToTable("conversion_requests", (string)null);
                });

            modelBuilder.Entity("EconomyService.Domain.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_code_platform")
                        .HasFilter("game_id IS NULL");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_currencies_game_id");

                    b.HasIndex("Code", "GameId")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_code_game_id")
                        .HasFilter("game_id IS NOT NULL");

                    b.ToTable("currencies", null, t =>
                        {
                            t.HasCheckConstraint("ck_currencies_scope_game_id", "(scope = 0 AND game_id IS NULL) OR (scope = 1 AND game_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EconomyService.Domain.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_ledger_entries_currency_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_entries_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("UserId", "CurrencyId")
                        .HasDatabaseName("ix_ledger_entries_user_id_currency_id");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("EconomyService.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("EconomyService.Inbox.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId")
                        .HasName("pk_processed_messages");

                    b.ToTable("processed_messages", (string)null);
                });

            modelBuilder.Entity("EconomyService.Domain.Balance", b =>
                {
                    b.HasOne("EconomyService.Domain.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_balances_currencies_currency_id");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("EconomyService.Domain.ConversionRate", b =>
                {
                    b.HasOne("EconomyService.Domain.Currency", "FromCurrency")
                        .WithMany()
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversion_rates_currencies_from_currency_id");

                    b.HasOne("EconomyService.Domain.Currency", "ToCurrency")
                        .WithMany()
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversion_rates_currencies_to_currency_id");

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("EconomyService.Domain.ConversionRequest", b =>
                {
                    b.HasOne("EconomyService.Domain.Currency", "FromCurrency")
                        .WithMany()
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversion_requests_currencies_from_currency_id");

                    b.HasOne("EconomyService.Domain.Currency", "ToCurrency")
                        .WithMany()
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversion_requests_currencies_to_currency_id");

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("EconomyService.Domain.LedgerEntry", b =>
                {
                    b.HasOne("EconomyService.Domain.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_currencies_currency_id");

                    b.Navigation("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
