apiVersion: v1
kind: ConfigMap
metadata:
  name: economy-config
  namespace: gaming-platform
data:
  POSTGRES_DB: "economy_db"
  POSTGRES_USER: "economy"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5001"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
