# Owned by economy-ci.yml. See ADR 0023.
deployments:
  economy-service:
    imageTag: cdab267b723f74a53ea74c232728abef52485ae5
migrationJobs:
  economy-migrator:
    imageTag: cdab267b723f74a53ea74c232728abef52485ae5
