{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gbp.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range $key, $route := .Values.ingress.hosts }}
    {{- if not (and (eq $key "mailpit") (not $.Values.mailpit.enabled)) }}
    - host: {{ $route.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $route.service }}
                port:
                  number: {{ $route.port }}
    {{- end }}
    {{- end }}
{{- end }}
